package main

import (
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/exec"
	"strconv"
	"time"

	"golang.org/x/net/proxy"
	tb "gopkg.in/tucnak/telebot.v2"
)

type Task struct {
	Pid     int
	CmdText string
	Cmd     *exec.Cmd
}

var (
	Bot   *tb.Bot
	Tasks []Task
)

func (t Task) String() string {
	return fmt.Sprintf("%v, %v", t.Pid, t.CmdText)
}

func parseCli() (string, int, string) {
	var token string
	var adminUserId int
	var proxy string
	flag.StringVar(&token, "token", "", "Bot token generated by BotFather")
	flag.IntVar(&adminUserId, "uid", 0, "Your telegram user id. Only enabled users can use this bot.")
	flag.StringVar(&proxy, "proxy", "", "Proxy(Socks5)")
	flag.Parse()
	return token, adminUserId, proxy
}

func init() {
	token, adminUserId, socks5 := parseCli()
	var err error
	if len(token) == 0 {
		token = os.Getenv("TELEGRAM_TOKEN")
	}
	if len(socks5) == 0 {
		socks5 = os.Getenv("PROXY_SOCKS5")
	}
	if adminUserId == 0 {
		adminUserId, err = strconv.Atoi(os.Getenv("ADMIN_USER_ID"))
		if err != nil {
			panic(err)
		}
	}

	poller := &tb.LongPoller{Timeout: 10 * time.Second}
	restricted := tb.NewMiddlewarePoller(poller, func(upd *tb.Update) bool {
		if upd.Message.Sender.ID != adminUserId {
			log.Printf("Unauthorized access denied for %d.\n", upd.Message.Sender.ID)
			return false
		}
		return true
	})

	botSettings := tb.Settings{
		Token:  token,
		Poller: restricted,
	}

	if socks5 != "" {
		log.Printf("Bot with proxy: %s\n", socks5)

		dialer, err := proxy.SOCKS5("tcp", socks5, nil, proxy.Direct)
		if err != nil {
			log.Fatal("Error creating dialer, aborting.")
		}

		httpTransport := &http.Transport{}
		httpClient := &http.Client{Transport: httpTransport}
		httpTransport.Dial = dialer.Dial
		botSettings.Client = httpClient

	} else {
		log.Printf("Bot with no proxy.\n")
	}

	Bot, err = tb.NewBot(botSettings)

	if err != nil {
		log.Fatal(err)
		return
	}
}
func makeHandle() {
	Bot.Handle("/start", handleHelp)
	Bot.Handle("/help", handleHelp)

	Bot.Handle("/tasks", handleTasks)
	Bot.Handle(tb.OnText, handleExecCommand)
}

func main() {
	makeHandle()
	Bot.Start()
}
